### ISSUE TITLE
Add public HTTP form support

### ISSUE THREAD

**Issue by barbie** [rjbs/CPAN-Uploader#12]
The git version and the live version are quite different, so didn't want to create a pull request which could break things for you. Hopefully the patch below is clear enough as to what I've done with my local copy, in the event that events like 2014-07-19 ever happen again!

--- /home/barbie/git/others/CPAN-Uploader/lib/CPAN/Uploader.pm  Tue Jul 22 08:00:52 2014
+++ Uploader.pm Tue Jul 22 08:01:48 2014
@@ -93,18 +93,33 @@

   my $uri = $self->{upload_uri} || $UPLOAD_URI;

-  my $request = POST(
-    $uri,
-    Content_Type => 'form-data',
-    Content      => {
+  my $type = 'form-data';
+  my $content = {
       HIDDENNAME                        => $self->{user},
       CAN_MULTIPART                     => 1,
       pause99_add_uri_upload            => File::Basename::basename($file),
-      SUBMIT_pause99_add_uri_httpupload => " Upload this file from my disk ",
-      pause99_add_uri_uri               => "",
       pause99_add_uri_httpupload        => [ $file ],
-      ($self->{subdir} ? (pause99_add_uri_subdirtext => $self->{subdir}) : ()),
-    },
+      pause99_add_uri_uri               => '',
+      SUBMIT_pause99_add_uri_httpupload => " Upload this file from my disk ",
+      ($self->{subdir} ? (pause99_add_uri_subdirtext        => $self->{subdir}) : ()),
+  };
+
+  if($file =~ m{^https?://}) {
+      $type = 'application/x-www-form-urlencoded';
+      $content = {
+          HIDDENNAME                        => $self->{user},
+          pause99_add_uri_httpupload        => '',
+          pause99_add_uri_uri               => $file,
+          SUBMIT_pause99_add_uri_uri        => " Upload this URL ",
+          ($self->{subdir} ? (pause99_add_uri_subdirtext        => $self->{subdir}) : ()),
+      };
+  }
+
+
+  my $request = POST(
+    $uri,
+    Content_Type => $type,
+    Content      => $content,
   );

   $request->authorization_basic($self->{user}, $self->{password});

This allowed me to type the following from the command line:

$> cpan-upload http://barbie.missbarbell.co.uk/releases/WWW-Scraper-ISBN-LOC_Driver-0.25.tar.gz

**Comment by rjbs** [comment]
thanks, merged, finally!
