### ISSUE TITLE
New warning during upload

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/CPAN-Uploader#27]
I got this error when performing an upload:

> Use of uninitialized value in numeric gt (>) at /Volumes/amaretto/Users/ether/.perlbrew/libs/31.11@std/lib/perl5/CPAN/Uploader.pm line 71.

This looks to be newly-introduced, via #21.  cc @perlancar

**Comment by perlancar** [comment]
commit 797695d introduced the warning.

**Comment by Leont** [comment]
Yeah, also seeing this issue

**Comment by rjbs** [comment]
Fixed by ed3b3b7?

**Comment by karenetheridge** [comment]
🤓🌻🦦
