### ISSUE TITLE
Exit code should be != 0 on failed uploads

### ISSUE THREAD

**Issue by eserte** [rjbs/CPAN-Uploader#30]
Just did the following session (CPAN::Uploader 0.103015 is installed here):
```
$ cpan-upload -d testdir test
PAUSE Password: 
```
(entered wrong password)
```
registering upload with PAUSE web server
POSTing upload for test to https://pause.perl.org/pause/authenquery?ACTION=add_uri
Upload failed (request failed with error code 401
  Message: Unauthorized
), will make attempt #1 ...
$ echo $?
0
```
Exit code should be non-zero after a failed upload.

Also, the message `will make attempt #1` looks wrong to me --- on a 401 there should be no other attempt, and if, it should be `#2`...

**Comment by theory** [comment]
I just noticed the same issue, which you can see in [this workflow](/pgxn/pgxn-site/runs/2580832581?check_suite_focus=true) that should have failed but did not (click "Release on CPAN").

**Comment by thibaultduponchelle** [comment]
I'm also very interested by this 👍🏼
