### ISSUE TITLE
Allow .pause config to configure other options, like http_proxy and upload_uri

### ISSUE THREAD

**Issue by preaction** [rjbs/CPAN-Uploader#9]
My work computer is behind a pretty nasty firewall, but I can disable it for temporary things provided I use the right proxy settings and do not use https. But I do not want to set these things in my dist.ini file, I would prefer to set them only in the .pause file on my work computer.

I'll try to prepare a patch.

**Comment by rjbs** [comment]
Closing this for lack of response.
